name: "Prestashop php-cs-fixer"
author: prestashop
description: "An easy way to run a configurable php-cs-fixer on your project without adding it as a dependency."
branding:
  icon: "check"
  color: "blue"
inputs:
  other-cmds:
    description: "Add some configs"
    required: false
    default: "/github/workspace --path-mode=intersection --dry-run --diff --using-cache=no --diff-format udiff"
  working-dir:
    description: "Working directory"
    required: false
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working-dir }}
    - ${{ inputs.other-cmds }}
